logging:
  level:
    com.xxy.gateway: debug
server:
  port: 10010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          # 写死不适合
#          uri: http://127.0.0.1:9091
          # 使用路由断言，配置映射路径
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          -filters:
             - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    instance:
      prefer-ip-address: true
