server:
  port: 8080
spring:
  application:
    name: consumer-demo #应用名称
eureka:
  client:
    service-url: #Eurekaserver地址
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 30 # 设置每隔30S重新拉取
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# 配置熔断策略：
hystrix:
  command:
    default:
      circuitBreaker:
        errorThresholdPercentage: 50 # 触发熔断错误比例阈值，默认值50%
        sleepWindowInMilliseconds: 10000 # 熔断后休眠时长，默认值5秒
        requestVolumeThreshold: 10 # 熔断触发最小请求次数，默认值是20
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 # 熔断超时设置，默认为1秒

